version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Docker/App.Dockerfile
    links:
      - psql
    environment:
      REDIS_URL: redis:6379
  psql:
    build:
      context: .
      dockerfile: Docker/PostgreSQL.Dockerfile